// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCruiserUserStories.DAO;

namespace MovieCruiserUserStories.Migrations
{
    [DbContext(typeof(DbCon))]
    [Migration("20200616105918_AddingFavorites123")]
    partial class AddingFavorites123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieCruiserUserStories.Models.Member", b =>
                {
                    b.Property<string>("userName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("confirmPassword");

                    b.Property<string>("firstName");

                    b.Property<string>("lastName");

                    b.Property<string>("password");

                    b.HasKey("userName");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("MovieCruiserUserStories.Models.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("BoxOffice");

                    b.Property<DateTime>("DateOfLaunch");

                    b.Property<string>("Genre");

                    b.Property<bool>("HasTeaser");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieCruiserUserStories.Models.WatchList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("DateOfLaunch");

                    b.Property<bool>("Favorite");

                    b.Property<string>("Genre");

                    b.Property<bool>("HasTeaser");

                    b.Property<int>("MovieId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("WatchList");
                });
#pragma warning restore 612, 618
        }
    }
}
